version: '3.1'

volumes:
  pg_exampleJava:

services:
  database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgre
      - POSTGRES_DB=database_SpringSecurity_PreProject_3
    volumes:
      - pg_exampleJava:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    restart: always
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/database_SpringSecurity_PreProject_3
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgre