volumes:
  pg_exampleJava:

services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env.prod
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pg_exampleJava:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    restart: always
    image: denis9834/application_5:latest
    ports:
      - "80:8080"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}