spring:
  liquibase:
    enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

server:
  port: 8080
  forward-headers-strategy: framework

logging:
  level:
    org:
      springframework:
        security: DEBUG
    liquibase: DEBUG

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}