name: Deploy Workflow

on:
  push: 
    branches: 
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build and push Docker Hub
        run: |
          docker build -t denis9834/application_5:latest .
          docker push denis9834/application_5:latest

      - name: Copy docker-compose.yml and .env.prod to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 194.87.99.49
          username: artur
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.yml,.env.prod"
          target: "/home/artur/myProject"

      - name: Deploy application
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 194.87.99.49
          username: artur
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/artur/myProject
            docker pull denis9834/application_5:latest
            set -a
            source .env.prod
            set +a
            docker-compose -f /home/artur/myProject/docker-compose.yml down
            docker-compose -f /home/artur/myProject/docker-compose-demo.yml down
            docker-compose -f /home/artur/myProject/docker-compose.yml up -d --build
            docker system prune -af
